### ISSUE TITLE
글 작성 시 맡은 역할?을 띄울 데이터가 없습니다. (하단의 front-end, android 부분)

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#126]
![image](https://user-images.githubusercontent.com/110771206/219564046-75a800a2-fa8c-4a65-ab3b-7db423593a6f.png)

**Comment by hyoloui** [comment]
단순하게 생각해서 이 부분 없으면 작성자가 글 작성시
함께한 사람들 부분에 추가하지 않을까 싶긴 합니다만..ㅠㅠ

**Comment by Jeremy-Kr** [comment]
디자인에 추가 되어서 클로즈 하겠습니다~
