### ISSUE TITLE
supabase DB created_at  시간 다르게 나오는 문제

### ISSUE THREAD

**Issue by hyoloui** [react-challengers/Codefolio#137]
post
![image](https://user-images.githubusercontent.com/115724947/219704748-bb63f19b-031d-458a-903e-dfcf24d391fe.png)

comment
![image](https://user-images.githubusercontent.com/115724947/219705025-9242d57c-ac24-4d25-a919-b11d7aa46fb1.png)

현재 post 와 comment에 있는 DB table에서 업로드 되는 default Value : now() 가
문제가 있어보입니다. 시간이 약 8~9 시간 느리네요

**Comment by Jeremy-Kr** [comment]
요뇨석은 어떤 문제인가용

**Comment by hyoloui** [comment]
post
![image](https://user-images.githubusercontent.com/115724947/219704748-bb63f19b-031d-458a-903e-dfcf24d391fe.png)

comment
![image](https://user-images.githubusercontent.com/115724947/219705025-9242d57c-ac24-4d25-a919-b11d7aa46fb1.png)

현재 post 와 comment에 있는 DB table에서 업로드 되는 default Value : now() 가
문제가 있어보입니다. 시간이 약 8~9 시간 느리네요

**Comment by Jeremy-Kr** [comment]
요고 아마 국제표준시 같은데 날짜 파싱할 때 toLocalString으로하면 잘 반영될까요?

기본값은 제 생각엔 tz? 설정하는거 있을것 같긴 한데 좀있다 찾아볼게요

**Comment by hyoloui** [comment]
https://choice91.tistory.com/49

**Comment by Jeremy-Kr** [comment]
https://supabase.com/docs/guides/database/managing-timezones
해당 문서를 참고해 SQL 데이터베이스의 시간을 한국으로 변경하는 문을 작성 하겠습니다.

**Comment by Jeremy-Kr** [comment]
```sql
alter database postgres
set timezone to 'ASIA/Seoul';
```
위와 같은 sql문을 추가 후 적용했고, 글쓰기 테스트 해 보니 시간 한국시간으로 정상적으로 들어오는 것 확인했습니다!
해당 이슈는 종료하도록 하겠습니다~
