### ISSUE TITLE
Next Image 경로 설정 문제

### ISSUE THREAD

**Issue by hyoloui** [react-challengers/Codefolio#141]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/115724947/219828626-23b2a3a1-a972-4b47-a5f9-fd965bbd4204.png">

참조 : https://nextjs.org/docs/messages/next-image-upgrade-to-13

`npx @next/codemod next-image-to-legacy-image .`
명령 시

모든 next/image 경로가 next/legacy/image로 변경
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/115724947/219828744-274960b7-576f-492e-85d1-9751c2d20580.png">

**Comment by Jeremy-Kr** [comment]
해당이슈 확인해보니 layout이라는 어트리뷰트를 사용해서 그런 것 같아요. 이게 구버전에서 지원하는건데 왜 지금 씀? 만약에 니가 의도한거면 구버전 image 컴포넌트 불러오셈~ 하는거 같은데 신버전 문법으로 리팩토링 필요해보입니다.

**Comment by Jeremy-Kr** [comment]
해당 이슈는 width와 height를 지정 해 주니 해결되네요~
따로 브랜치 따서 커밋 날리겠습니다~~
