### ISSUE TITLE
toast UI Editor 작성중 영역 (노란 박스) 사용 여부 의사결정

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#162]
# 텍스트 에디터에 변경되는 블록이 하이라이트 되는 이슈입니다.
![01 코드하이라이트](https://user-images.githubusercontent.com/110771206/220254546-35fa49c9-3524-4e4b-9caf-c79fb9f2ef78.gif)

해당 부분에 대한 의견을 댓글로 남겨 주세요.

**Comment by arch-spatula** [comment]
블록 하이라이트는 괜찮은 것 같아요

**Comment by Jeremy-Kr** [comment]
개인적으로는 현행 유지가 좋다고 생각합니다.

**Comment by yunjunhojj** [comment]
저도 블록 있는 것 찬성 (현행)

**Comment by hyoloui** [comment]
네 동의합니다!!

**Comment by Jeremy-Kr** [comment]
해당 이슈 3진 동의로 아웃합니다
