### ISSUE TITLE
태그 갯수 제한

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#163]
`개발 스택` 등 밀려나는 노드들에 대해 min-width or min-height를 추가하여 해결하면 됩니다.

**Comment by arch-spatula** [comment]
`min-width` 변경 좋습니다.

**Comment by arch-spatula** [comment]
![스크린샷 2023-02-21 오후 4 31 46](https://user-images.githubusercontent.com/84452145/220277559-258e37ca-492a-4cc8-ac84-3ff6bc0b2753.png)

**Comment by arch-spatula** [comment]
![스크린샷 2023-02-21 오후 4 32 24](https://user-images.githubusercontent.com/84452145/220277699-7cb46c77-72f6-4339-9098-74b8c7cddfd8.png)
