### ISSUE TITLE
디테일 페이지 칭찬뱃지 모달 위치 변경

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#263]
```sh
git checkout -b "fix/BadgeModalPosition"
```

**Comment by arch-spatula** [comment]
<img width="1582" alt="스크린샷 2023-03-04 오후 7 35 37" src="https://user-images.githubusercontent.com/84452145/222894911-3e21dfeb-8b60-4bf4-ae29-92137fb7fc99.png">

<img width="1582" alt="스크린샷 2023-03-04 오후 7 35 56" src="https://user-images.githubusercontent.com/84452145/222894972-e1b39829-d36f-4d85-8c21-c547e6d1cb18.png">
