### ISSUE TITLE
main page min-height 추가(게시글 없으면 푸터가 위에 친구들이랑 친해짐)

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#265]

**Comment by arch-spatula** [comment]
# 기존

<img width="1582" alt="스크린샷 2023-03-04 오후 8 37 14" src="https://user-images.githubusercontent.com/84452145/222897739-db07377c-a8f9-48db-8b61-3b7cdca6ec15.png">

# 수정

<img width="1582" alt="스크린샷 2023-03-04 오후 8 37 41" src="https://user-images.githubusercontent.com/84452145/222897754-8c2d2b3e-8d73-4c67-8045-cfd7abe757ff.png">
