### ISSUE TITLE
함께한 사람들 최초 진입시 본인 프로필 못불러오는 현상

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#271]

**Comment by hyoloui** [comment]
![Mar-05-2023 03-26-07](https://user-images.githubusercontent.com/115724947/222922841-7ce772ad-d485-4dd9-8b97-18c9e40816ff.gif)

![#271](https://user-images.githubusercontent.com/115724947/222923255-ebbcb981-ed74-4f3b-ae59-f25b4175ebde.png)

유저 정보가 늦게 들어오는데 어떻게 해결하면 좋을까요..
유저용 JSX 를 따로 그려줘야 할까요?
