### ISSUE TITLE
함께한사람들 참여포지션 드롭다운으로 변경

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#277]

**Comment by Jeremy-Kr** [comment]
승효님 PR 완료되면 진행하겠습니다

**Comment by hyoloui** [comment]
@Jeremy-Kr 작업중 입니다!

**Comment by hyoloui** [comment]
작업 완료 했으나, 

post 컬럼 수정으로 빌드 에러 발생합니다.

sub category 삭제
large category -> category
