### ISSUE TITLE
캐러셀 라이브러리 선정

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#44]
# 캐러셀 라이브러리를 선정하기 위한 이슈입니다.
## 대표적인 캐러셀 라이브러리들의 npm trend

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/110771206/218669988-ba1c4bef-317e-4fbc-9da3-e950cf4ce0bb.png">

- 위 트랜드를 바탕으로 선택지를 줄이기 위해 상위 2개의 라이브러리를 비교하고자 합니다.
- [단순 지표 비교표](https://js.libhunt.com/compare-slick-vs-swiper)

### 1. swiper
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/110771206/218670211-33b62bfc-2740-4400-ad74-6226494dadfc.png">

[공식웹사이트](https://swiperjs.com/)
[사용 레퍼런스 블로그](https://velog.io/@merorii/Next.js-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-carousel-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-react-slick)
- 대표적인 캐러셀 라이브러리. 대부분의 상황에서 적용이 가능합니다.
- React를 공식적인 내장 기능으로 지원합니다.
- 다양한 설정을 할 수 있는 만큼 복잡합니다.

### 2. slick-carousel
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/110771206/218671892-39e47724-f564-47c1-b6ad-166c083599ee.png">

[공식웹사이트](http://kenwheeler.github.io/slick/)
[사용 레퍼런스 블로그](https://darrengwon.tistory.com/283)

- 제이쿼리 의존성이 강한 바닐라JS용 라이브러리입니다.
- React와 함께 사용하려면 react-slick를 사용할 수 있습니다. [react-slick](https://react-slick.neostack.com/)
- 다양한 설정을 하기는 어렵지만 단순합니다.

---
## 결론
- 여러 방면에서 보았을 때, 다양한 설정을 지원하는 swiper를 도입하는게 초기 셋업 비용은 들지만 현명해 보입니다.
- 만일 단순하게 디테일 페이지에서만 캐러셀을 사용하고, 크게 커스터마이징이 들어가지 않는다면 react-slick의 도입을 고려해 볼 만한 것 같습니다.
- 위 사항들에 대해서 확인 해 주시고, 댓글로 의견 부탁드립니다.

@yunjunhojj @nno3onn @arch-spatula @hyoloui

**Comment by hyoloui** [comment]
참고로 디테일 페이지에서 이루어지는 인터렉션 입니다!

**Comment by arch-spatula** [comment]
swiper

**Comment by yunjunhojj** [comment]
swiper 사용하면 best 일 것 같습니다!

**Comment by nno3onn** [comment]
swiper에 동의합니다

**Comment by Jeremy-Kr** [comment]
여러분의 성원에 힘입어 swiper로 결정하겠읍니다. 감사합니다.
