### ISSUE TITLE
modal의 url을 통한 관리를 위한 jotai 도입 건

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#49]
# 본 이슈는 modal의 관리를 위해 jotai를 도입하는 것을 고려하는 이슈입니다.

## 배경
behance등 여타 글로벌 플랫폼에서 모달의 히스토리를 url로 관리하는것을 참고하였고, 데모는 아래와 같습니다.

![Feb-15-2023 10-01-03](https://user-images.githubusercontent.com/110771206/218898088-bfd198ac-a347-4efe-8f76-24fd38204a11.gif)

위와 같은 방식을 서치하다 보니 [아티클](https://ui.toast.com/posts/ko_20211214)을 발견하게 되었고, jotai에서 제공해주는 util을 활용하면 쉽게 적용이 가능해 질 것 같다는 판단이 들어 이슈를 생성하게 되었습니다.

## 적용 시기 논의
- 현재 진행하고있는 1.0.0 배포 사이클에서는 적용하는게 부담스러울 것 같다는 판단이 들고, 1.1.0 업데이트 시점에 recoil -> jotai로 리팩토링 하는 쪽이 좋아 보인다는 의견입니다.
- 만일, 이 안건이 적용된다면 1.0.0 배포 이후 유져 피드백 수집기간 및 1.1.0 설계 시점에 리팩토링이 진행되게 될 것 같습니다.

## 발생하는 비용
- 현재 글로벌로 관리하고 있는 state가 방대하지 않으므로 큰 비용이 발생하진 않으리라 예상됩니다.
- 다만, recoil에서 jotai로 넘어가며 팀원들의 학습이 필요한 상황이라 학습에 대한 비용이 발생하게 될것으로 예상됩니다.

## 결론
- 1.0.0 배포가 끝난 이후 이 이슈를 통해 논의를 진행하고 적용 방향을 논의하는것이 바람직하다는 의견입니다.

**Comment by hyoloui** [comment]
확인 했습니다!

**Comment by arch-spatula** [comment]
이슈 좋습니다.

**Comment by yunjunhojj** [comment]
해당 내용을 리코일로 해결이 된 건가요? 이미 구현 하신 것 같아서 여쭤보기

**Comment by Jeremy-Kr** [comment]
해당 이슈는 일단 next/router를 통해서 구현 되었습니다. 추후 리팩토링이 필요할 시 다시 jotai 도입건을 논의 해 보는게 좋을 것 같아 이슈 클로즈 시키겠습니다.
