### ISSUE TITLE
(이슈 삭제 부탁합니다)

### ISSUE THREAD

**Issue by arch-spatula** [react-challengers/Codefolio#56]

**Comment by hyoloui** [comment]
Terminal 에서 yarn 명령어로 업데이트 하면 react-query가 설치되어 해당 오류 해결됩니다! @arch-spatula

**Comment by hyoloui** [comment]
```yarn```

**Comment by yunjunhojj** [comment]
댓글 CRUD 과정에서 리액트 쿼리를 새로 설치해서 그런가봐요!
